### ISSUE TITLE
Error:  Notice: SoapClient::__doRequest(): send of 1352 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by albertski** [albertski/ExperientBundle#2]
When processing a lot of records my script fails and I get the following message: 
Notice: SoapClient::__doRequest(): send of 1352 bytes failed with errno=32 Broken pipe

**Comment by albertski** [comment]
Made change as recommended [here](https://bugs.php.net/bug.php?id=60329).

**Comment by MatheusNaldi** [comment]
Saved my day

**Comment by msanchezcodoni** [comment]
Thanks!
